### ISSUE TITLE
Change request: Rename the regex function

### ISSUE THREAD

**Issue by dertuxmalwieder** [AccelerationNet/cl-mediawiki#11]
Currently one can't use `cl-mediawiki` and `cl-ppcre` at the same time because of a function naming conflict. You might want to change that.

**Comment by bobbysmith007** [comment]
This is the exact reason for the existence of package system in common lisp. I would suggest not "use"ing cl-mediawiki and instead prefixing calls to the api with "cl-mediawiki:" if you really must "use" both, add a :shadow keyword for which ever symbol you dont want locally available. Obviously your local package can choose to define whatever names it wants to call this functions.

**Comment by bobbysmith007** [comment]
http://www.gigamonkeys.com/book/programming-in-the-large-packages-and-symbols.html

**Comment by dertuxmalwieder** [comment]
Good point, thank you.
